export const GAME_ASSETS = {
  player: '/assets/png/default/ships/ship_6.png',
  chaser: '/assets/png/default/ships/ship_16.png',
  shooter: '/assets/png/default/ships/ship_22.png',
  cannonBall: '/assets/png/default/ship_parts/cannon_ball.png',
  explosion: '/assets/png/default/effects/explosion_1.png',
  fire: '/assets/png/default/effects/fire_1.png',
  damagePortraits: [
    '/assets/ui/damage-panel-1-2x.png',
    '/assets/ui/damage-panel-2-2x.png',
    '/assets/ui/damage-panel-3-2x.png',
    '/assets/ui/damage-panel-4-2x.png',
    '/assets/ui/damage-panel-5-2x.png',
  ],
  victoryPortraits: [
    '/assets/ui/victory-panel-1-2x.png',
    '/assets/ui/victory-panel-2-2x.png',
    '/assets/ui/victory-panel-3-2x.png',
    '/assets/ui/victory-panel-4-2x.png',
    '/assets/ui/victory-panel-5-2x.png',
  ],
  idlePortraits: [
    '/assets/ui/idle-panel-1-2x.png',
    '/assets/ui/idle-panel-2-2x.png',
    '/assets/ui/idle-panel-3-2x.png',
    '/assets/ui/idle-panel-4-2x.png',
    '/assets/ui/idle-panel-5-2x.png',
    '/assets/ui/idle-panel-6-2x.png',
    '/assets/ui/idle-panel-7-2x.png',
    '/assets/ui/idle-panel-8-2x.png',
    '/assets/ui/idle-panel-9-2x.png',
    '/assets/ui/idle-panel-10-2x.png',
  ],
  mechanicPortraits: {
    dash: '/assets/ui/mechanic-dash-panel.png',
    medicine: '/assets/ui/mechanic-medicine-panel.png',
    powder: '/assets/ui/mechanic-powder-panel.png',
    wind: '/assets/ui/mechanic-wind-panel.png',
    armor: '/assets/ui/mechanic-armor-panel.png',
    barrel: '/assets/ui/mechanic-barrel-panel.png',
  },
  shotSound: '/assets/sounds/cannon_fire_1.wav',
  broadsideSound: '/assets/sounds/cannon_broadside.wav',
  explosionSound: '/assets/sounds/ship_explosion_1.wav',
  hitSounds: [
    '/assets/sounds/ship_wood_hit_1.wav',
    '/assets/sounds/ship_wood_hit_2.wav',
  ],
  collisionSound: '/assets/sounds/ship_collision.wav',
  idleChirpSound: '/assets/sounds/idle_captain_chirp.wav',
  pickupSound: '/assets/sounds/pickup_chime.wav',
  dashSound: '/assets/sounds/dash_whoosh.wav',
} as const;
