export const GAME_ASSETS = {
  player: '/assets/png/default/ships/ship_6.png',
  chaser: '/assets/png/default/ships/ship_16.png',
  shooter: '/assets/png/default/ships/ship_22.png',
  cannonBall: '/assets/png/default/ship_parts/cannon_ball.png',
  explosion: '/assets/png/default/effects/explosion_1.png',
  fire: '/assets/png/default/effects/fire_1.png',
  damagePortraits: [
    '/assets/ui/react-damage-01.png',
    '/assets/ui/react-damage-02.png',
    '/assets/ui/react-damage-03.png',
    '/assets/ui/react-damage-04.png',
    '/assets/ui/react-damage-05.png',
  ],
  victoryPortraits: [
    '/assets/ui/react-victory-01.png',
    '/assets/ui/react-victory-02.png',
    '/assets/ui/react-victory-03.png',
    '/assets/ui/react-victory-04.png',
    '/assets/ui/react-victory-05.png',
  ],
  idlePortraits: [
    '/assets/ui/react-idle-01.png',
    '/assets/ui/react-idle-02.png',
    '/assets/ui/react-idle-03.png',
    '/assets/ui/react-idle-04.png',
    '/assets/ui/react-idle-05.png',
    '/assets/ui/react-idle-06.png',
    '/assets/ui/react-idle-07.png',
    '/assets/ui/react-idle-08.png',
    '/assets/ui/react-idle-09.png',
    '/assets/ui/react-idle-10.png',
  ],
  mechanicPortraits: {
    dash: '/assets/ui/react-mechanic-dash.png',
    medicine: '/assets/ui/react-mechanic-medicine.png',
    powder: '/assets/ui/react-mechanic-powder.png',
    wind: '/assets/ui/react-mechanic-wind.png',
    armor: '/assets/ui/react-mechanic-armor.png',
    barrel: '/assets/ui/react-mechanic-barrel.png',
  },
  shotSound: '/assets/sounds/cannon_fire_1.wav',
  broadsideSound: '/assets/sounds/cannon_broadside.wav',
  explosionSound: '/assets/sounds/ship_explosion_1.wav',
  hitSounds: [
    '/assets/sounds/ship_wood_hit_1.wav',
    '/assets/sounds/ship_wood_hit_2.wav',
  ],
  collisionSound: '/assets/sounds/ship_collision.wav',
  idleChirpSound: '/assets/sounds/idle_captain_chirp.wav',
  pickupSound: '/assets/sounds/pickup_chime.wav',
  dashSound: '/assets/sounds/dash_whoosh.wav',
} as const;
